language: ruby
rvm:
  - 1.9.3
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rake
before_script:
  - psql -c 'create database octopub_test;' -U postgres
env:
  global:
    - secure: "t5WExrWdydqqqUmNuxh6mCXVb6uOY69iLsFua+Uy/HHOnzefYLRrneUsvrY1\nsMD0AaCy1cfsTU4fAFA2OsrVRca4fFBnnrxnWXuqPLJbCQbXj0ZYoJZcrGVc\nm9ZSoRaMlAF1g/SVm7CAiquQnfoomaj1Cvl/R7doAvy7tNkyLtc="
    - secure: "dIxmbccpV2Rt0xEL8NSTD2eL3Wefyg+HWxoZFLyn9zibzGj7XSIIuccNSGlX\nyDKhtFLdVppmHpU1ZkyUGavxovxWrfea2Fe/Mk8LgQ/1AEfdNUJ6VBLZy416\nq2gM3+FgmuRZW83k2jK2MQcCqWH8l/twhZeItPjbpf5Em1p3Bs8="
    - secure: "VWS7ckWY7weM3XODvv2zD3fkzj8u8MFW7Hpp9NyZOsgcIXPneNKmrC985RMz\n0dqMKGvbsV9rlvcTa672UrQg4x6O/VWDrD96IkG0b3KqBJdLFvWctQdORY4C\nsdZBJb3Qg+fxi3J/iP0GvVLosYCc2neUaHXXdhd02ooscjIcYw8="
    - secure: "ODB3uNs155ZL2bC3iRZYksAf09OrA1GzDBu5cKtJuw4h/DRQVPqo9ZLYYJ5Z\nGv/eJ41Vw/kYOG/3HJev3KSavrNlqzt03Pea8iYzOjPcx3F5Klc0Gb1SHLkW\nSvMLOiTP8wvB9mZnyRtIVhYRvfaGIKFlSJw3J+mD9DZbtaKN/jE="
