module Octopub
  class Blog < Struct.new(:user, :repo, :github)
    def clone_octopress
      Octopub::OctopressCloner.clone
      tree = Octopub::TreeBuilder.build('tmp/octopress')
      commit(tree)
    end

    def commit(tree, message="Octopub autogenerated commit.")
      latest_commit = github.git_data.references.
        get(user, repo, 'heads/master')['object']['sha']

      new_tree = github.git_data.trees.
        create(user, repo, tree: tree)['sha']

      new_commit = github.git_data.commits.
        create(user, repo,
               parents: [latest_commit],
               tree: new_tree,
               message: message)['sha']

      github.git_data.references.
        update(user, repo, 'heads/master', sha: new_commit, force: true)
    end
  end
end
